### ISSUE TITLE
Qgis 3

### ISSUE THREAD

**Issue by pekouille** [ANAT01/qgis-plugin-point2one#1]
Hi !

I would like to know if you plan to update points2one to qgis 3 ?
Anyway, thanks a lot for this plugin, I have been using it A LOT these past years and it really was useful to me and my collegues ! 

Laurent Wilket

**Comment by ANAT01** [comment]
Hi,

It's just a fork of original plugin https://launchpad.net/points2one
I'm not use qgis3 and original author say that he haven't time to release qgis3 compatible. https://bugs.launchpad.net/points2one/+bug/1764747

You can try to do it yourself ;)

**Comment by ANAT01** [comment]
Processing -> Toolbox -> Vector creation -> Points to path

![pointstopath](https://user-images.githubusercontent.com/7475811/54883543-4b752d00-4e88-11e9-8a0d-607e76faa3ae.gif)
